file_format: "1"
id: ChocX
name: ChocX
type: shield
url: https://github.com/HNH-NASA/zmk-config-chocx-test
features:
  - keys
requires:
  - seeeduino_xiao_ble
  - az1uball
siblings:
  - ChocX_L
  - ChocX_R